"""empty message

Revision ID: 739ff5e1bd44
Revises: 9e4750c23b9a
Create Date: 2024-10-13 18:57:54.702718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739ff5e1bd44'
down_revision = '9e4750c23b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
